// Mock data for Dayflow HRMS

export type UserRole = 'admin' | 'hr' | 'employee';

export type AttendanceStatus = 'present' | 'leave' | 'absent';

export interface Employee {
  id: string;
  loginId: string;
  name: string;
  email: string;
  phone: string;
  avatar: string;
  designation: string;
  department: string;
  company: string;
  manager: string;
  location: string;
  dateOfJoining: string;
  status: AttendanceStatus;
  // Private info
  dateOfBirth: string;
  address: string;
  nationality: string;
  personalEmail: string;
  gender: string;
  maritalStatus: string;
  // Bank details
  bankName: string;
  accountNumber: string;
  ifscCode: string;
  panNo: string;
  uanNo: string;
  empCode: string;
  // Resume
  about: string;
  whatILove: string;
  interests: string;
  skills: string[];
  certifications: string[];
  // Salary (admin only)
  basicSalary: number;
  hra: number;
  standardAllowance: number;
  performanceBonus: number;
  lta: number;
  fixedAllowance: number;
  pfEmployee: number;
  pfEmployer: number;
  professionalTax: number;
}

export interface AttendanceRecord {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string;
  checkIn: string | null;
  checkOut: string | null;
  workHours: string;
  extraHours: string;
}

export interface TimeOffRequest {
  id: string;
  employeeId: string;
  employeeName: string;
  startDate: string;
  endDate: string;
  type: 'paid' | 'sick' | 'unpaid';
  status: 'pending' | 'approved' | 'rejected';
  days: number;
}

// Generate avatar URL from name
const getAvatar = (name: string) => 
  `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(name)}`;

export const employees: Employee[] = [
  {
    id: '1',
    loginId: 'DAYARO20230001',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@dayflow.com',
    phone: '+91 98765 43210',
    avatar: getAvatar('Arjun Sharma'),
    designation: 'Senior Software Engineer',
    department: 'Engineering',
    company: 'Dayflow Technologies',
    manager: 'Priya Patel',
    location: 'Mumbai, India',
    dateOfJoining: '2023-01-15',
    status: 'present',
    dateOfBirth: '1992-05-20',
    address: '42 Tech Park, Andheri East, Mumbai 400069',
    nationality: 'Indian',
    personalEmail: 'arjun.personal@gmail.com',
    gender: 'Male',
    maritalStatus: 'Married',
    bankName: 'HDFC Bank',
    accountNumber: '****5678',
    ifscCode: 'HDFC0001234',
    panNo: 'ABCDE1234F',
    uanNo: '100123456789',
    empCode: 'EMP001',
    about: 'Passionate software engineer with 6+ years of experience in building scalable web applications. Love working with modern technologies and mentoring junior developers.',
    whatILove: 'The collaborative culture and the opportunity to work on challenging projects that make a real impact.',
    interests: 'Open source contribution, hiking, photography, playing guitar',
    skills: ['React', 'TypeScript', 'Node.js', 'Python', 'AWS', 'PostgreSQL'],
    certifications: ['AWS Solutions Architect', 'Google Cloud Professional'],
    basicSalary: 50000,
    hra: 20000,
    standardAllowance: 10000,
    performanceBonus: 5000,
    lta: 3000,
    fixedAllowance: 2000,
    pfEmployee: 6000,
    pfEmployer: 6000,
    professionalTax: 200,
  },
  {
    id: '2',
    loginId: 'DAYPPA20230002',
    name: 'Priya Patel',
    email: 'priya.patel@dayflow.com',
    phone: '+91 98765 43211',
    avatar: getAvatar('Priya Patel'),
    designation: 'Engineering Manager',
    department: 'Engineering',
    company: 'Dayflow Technologies',
    manager: 'Rajesh Kumar',
    location: 'Mumbai, India',
    dateOfJoining: '2022-06-01',
    status: 'present',
    dateOfBirth: '1988-11-15',
    address: '15 Palm Heights, Powai, Mumbai 400076',
    nationality: 'Indian',
    personalEmail: 'priya.pp@gmail.com',
    gender: 'Female',
    maritalStatus: 'Married',
    bankName: 'ICICI Bank',
    accountNumber: '****9012',
    ifscCode: 'ICIC0001234',
    panNo: 'FGHIJ5678K',
    uanNo: '100123456790',
    empCode: 'EMP002',
    about: 'Engineering leader focused on building high-performing teams. 10+ years in tech with experience at startups and enterprises.',
    whatILove: 'Seeing team members grow and watching projects come to life.',
    interests: 'Leadership podcasts, yoga, travel, cooking',
    skills: ['Team Leadership', 'Agile', 'System Design', 'Java', 'Microservices'],
    certifications: ['PMP', 'Scrum Master'],
    basicSalary: 80000,
    hra: 32000,
    standardAllowance: 15000,
    performanceBonus: 10000,
    lta: 5000,
    fixedAllowance: 3000,
    pfEmployee: 9600,
    pfEmployer: 9600,
    professionalTax: 200,
  },
  {
    id: '3',
    loginId: 'DAYRKR20220003',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@dayflow.com',
    phone: '+91 98765 43212',
    avatar: getAvatar('Rajesh Kumar'),
    designation: 'CTO',
    department: 'Executive',
    company: 'Dayflow Technologies',
    manager: '-',
    location: 'Mumbai, India',
    dateOfJoining: '2020-01-01',
    status: 'leave',
    dateOfBirth: '1980-03-25',
    address: '8 Sea View, Worli, Mumbai 400018',
    nationality: 'Indian',
    personalEmail: 'rajesh.k@gmail.com',
    gender: 'Male',
    maritalStatus: 'Married',
    bankName: 'SBI',
    accountNumber: '****3456',
    ifscCode: 'SBIN0001234',
    panNo: 'LMNOP9012Q',
    uanNo: '100123456791',
    empCode: 'EMP003',
    about: 'Technology visionary with 20+ years of experience. Built multiple successful products from ground up.',
    whatILove: 'Defining technical strategy and seeing the company grow.',
    interests: 'AI/ML research, chess, golf, reading',
    skills: ['Strategy', 'Architecture', 'AI/ML', 'Cloud', 'Leadership'],
    certifications: ['MBA - IIM Ahmedabad'],
    basicSalary: 200000,
    hra: 80000,
    standardAllowance: 40000,
    performanceBonus: 50000,
    lta: 20000,
    fixedAllowance: 10000,
    pfEmployee: 15000,
    pfEmployer: 15000,
    professionalTax: 200,
  },
  {
    id: '4',
    loginId: 'DAYSMN20230004',
    name: 'Sneha Menon',
    email: 'sneha.menon@dayflow.com',
    phone: '+91 98765 43213',
    avatar: getAvatar('Sneha Menon'),
    designation: 'HR Manager',
    department: 'Human Resources',
    company: 'Dayflow Technologies',
    manager: 'Rajesh Kumar',
    location: 'Mumbai, India',
    dateOfJoining: '2023-02-15',
    status: 'present',
    dateOfBirth: '1990-08-12',
    address: '22 Green Park, Bandra, Mumbai 400050',
    nationality: 'Indian',
    personalEmail: 'sneha.m@gmail.com',
    gender: 'Female',
    maritalStatus: 'Single',
    bankName: 'Axis Bank',
    accountNumber: '****7890',
    ifscCode: 'UTIB0001234',
    panNo: 'RSTUV3456W',
    uanNo: '100123456792',
    empCode: 'EMP004',
    about: 'People-first HR professional passionate about creating positive workplace cultures.',
    whatILove: 'Helping employees thrive and building a great company culture.',
    interests: 'Employee wellness, dance, painting, volunteering',
    skills: ['Recruitment', 'Employee Relations', 'HRIS', 'Compliance', 'Training'],
    certifications: ['SHRM-CP', 'HR Analytics'],
    basicSalary: 60000,
    hra: 24000,
    standardAllowance: 12000,
    performanceBonus: 6000,
    lta: 4000,
    fixedAllowance: 2500,
    pfEmployee: 7200,
    pfEmployer: 7200,
    professionalTax: 200,
  },
  {
    id: '5',
    loginId: 'DAYAMG20230005',
    name: 'Amit Gupta',
    email: 'amit.gupta@dayflow.com',
    phone: '+91 98765 43214',
    avatar: getAvatar('Amit Gupta'),
    designation: 'Product Designer',
    department: 'Design',
    company: 'Dayflow Technologies',
    manager: 'Priya Patel',
    location: 'Bangalore, India',
    dateOfJoining: '2023-04-01',
    status: 'absent',
    dateOfBirth: '1995-01-30',
    address: '55 Koramangala, Bangalore 560034',
    nationality: 'Indian',
    personalEmail: 'amit.g@gmail.com',
    gender: 'Male',
    maritalStatus: 'Single',
    bankName: 'Kotak Bank',
    accountNumber: '****2345',
    ifscCode: 'KKBK0001234',
    panNo: 'XYZAB6789C',
    uanNo: '100123456793',
    empCode: 'EMP005',
    about: 'Creative designer with an eye for detail. Passionate about creating beautiful and functional user experiences.',
    whatILove: 'Turning complex problems into simple, elegant solutions.',
    interests: 'UI design trends, sketching, gaming, movies',
    skills: ['Figma', 'UI/UX', 'Design Systems', 'Prototyping', 'User Research'],
    certifications: ['Google UX Design Certificate'],
    basicSalary: 55000,
    hra: 22000,
    standardAllowance: 11000,
    performanceBonus: 5500,
    lta: 3500,
    fixedAllowance: 2200,
    pfEmployee: 6600,
    pfEmployer: 6600,
    professionalTax: 200,
  },
  {
    id: '6',
    loginId: 'DAYNSR20230006',
    name: 'Neha Srivastava',
    email: 'neha.srivastava@dayflow.com',
    phone: '+91 98765 43215',
    avatar: getAvatar('Neha Srivastava'),
    designation: 'Frontend Developer',
    department: 'Engineering',
    company: 'Dayflow Technologies',
    manager: 'Arjun Sharma',
    location: 'Mumbai, India',
    dateOfJoining: '2023-07-10',
    status: 'present',
    dateOfBirth: '1997-09-05',
    address: '10 Lake View, Thane 400601',
    nationality: 'Indian',
    personalEmail: 'neha.s@gmail.com',
    gender: 'Female',
    maritalStatus: 'Single',
    bankName: 'HDFC Bank',
    accountNumber: '****6789',
    ifscCode: 'HDFC0005678',
    panNo: 'DEFGH0123I',
    uanNo: '100123456794',
    empCode: 'EMP006',
    about: 'Frontend enthusiast who loves creating pixel-perfect interfaces. Always learning new technologies.',
    whatILove: 'The fast-paced environment and supportive team.',
    interests: 'Web development, blogging, fitness, music',
    skills: ['React', 'Vue.js', 'CSS', 'JavaScript', 'Tailwind'],
    certifications: ['Meta Frontend Developer'],
    basicSalary: 45000,
    hra: 18000,
    standardAllowance: 9000,
    performanceBonus: 4500,
    lta: 2800,
    fixedAllowance: 1800,
    pfEmployee: 5400,
    pfEmployer: 5400,
    professionalTax: 200,
  },
  {
    id: '7',
    loginId: 'DAYVRD20230007',
    name: 'Vikram Reddy',
    email: 'vikram.reddy@dayflow.com',
    phone: '+91 98765 43216',
    avatar: getAvatar('Vikram Reddy'),
    designation: 'DevOps Engineer',
    department: 'Engineering',
    company: 'Dayflow Technologies',
    manager: 'Priya Patel',
    location: 'Hyderabad, India',
    dateOfJoining: '2023-03-20',
    status: 'present',
    dateOfBirth: '1993-12-18',
    address: '88 Hi-Tech City, Hyderabad 500081',
    nationality: 'Indian',
    personalEmail: 'vikram.r@gmail.com',
    gender: 'Male',
    maritalStatus: 'Married',
    bankName: 'SBI',
    accountNumber: '****0123',
    ifscCode: 'SBIN0005678',
    panNo: 'JKLMN4567O',
    uanNo: '100123456795',
    empCode: 'EMP007',
    about: 'Infrastructure specialist focused on automation and reliability. Love building robust CI/CD pipelines.',
    whatILove: 'Solving complex infrastructure challenges.',
    interests: 'Automation, Linux, cricket, cooking',
    skills: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'Jenkins'],
    certifications: ['AWS DevOps Professional', 'CKA'],
    basicSalary: 65000,
    hra: 26000,
    standardAllowance: 13000,
    performanceBonus: 6500,
    lta: 4000,
    fixedAllowance: 2600,
    pfEmployee: 7800,
    pfEmployer: 7800,
    professionalTax: 200,
  },
  {
    id: '8',
    loginId: 'DAYASN20230008',
    name: 'Ananya Singh',
    email: 'ananya.singh@dayflow.com',
    phone: '+91 98765 43217',
    avatar: getAvatar('Ananya Singh'),
    designation: 'QA Engineer',
    department: 'Engineering',
    company: 'Dayflow Technologies',
    manager: 'Priya Patel',
    location: 'Delhi, India',
    dateOfJoining: '2023-05-15',
    status: 'leave',
    dateOfBirth: '1994-07-22',
    address: '25 Connaught Place, New Delhi 110001',
    nationality: 'Indian',
    personalEmail: 'ananya.s@gmail.com',
    gender: 'Female',
    maritalStatus: 'Single',
    bankName: 'PNB',
    accountNumber: '****4567',
    ifscCode: 'PUNB0001234',
    panNo: 'PQRST8901U',
    uanNo: '100123456796',
    empCode: 'EMP008',
    about: 'Quality advocate with strong attention to detail. Experienced in both manual and automated testing.',
    whatILove: 'Finding bugs before users do!',
    interests: 'Test automation, reading, travel, photography',
    skills: ['Selenium', 'Cypress', 'API Testing', 'Performance Testing', 'Agile'],
    certifications: ['ISTQB Foundation'],
    basicSalary: 48000,
    hra: 19200,
    standardAllowance: 9600,
    performanceBonus: 4800,
    lta: 3000,
    fixedAllowance: 1900,
    pfEmployee: 5760,
    pfEmployer: 5760,
    professionalTax: 200,
  },
  {
    id: '9',
    loginId: 'DAYRKH20230009',
    name: 'Rohan Khanna',
    email: 'rohan.khanna@dayflow.com',
    phone: '+91 98765 43218',
    avatar: getAvatar('Rohan Khanna'),
    designation: 'Backend Developer',
    department: 'Engineering',
    company: 'Dayflow Technologies',
    manager: 'Arjun Sharma',
    location: 'Mumbai, India',
    dateOfJoining: '2023-08-01',
    status: 'present',
    dateOfBirth: '1996-04-10',
    address: '30 Malad West, Mumbai 400064',
    nationality: 'Indian',
    personalEmail: 'rohan.k@gmail.com',
    gender: 'Male',
    maritalStatus: 'Single',
    bankName: 'ICICI Bank',
    accountNumber: '****8901',
    ifscCode: 'ICIC0005678',
    panNo: 'VWXYZ2345A',
    uanNo: '100123456797',
    empCode: 'EMP009',
    about: 'Backend developer passionate about building scalable APIs and microservices.',
    whatILove: 'The technical challenges and great team dynamics.',
    interests: 'System design, podcasts, basketball, gaming',
    skills: ['Node.js', 'Python', 'PostgreSQL', 'Redis', 'GraphQL'],
    certifications: ['MongoDB Certified Developer'],
    basicSalary: 52000,
    hra: 20800,
    standardAllowance: 10400,
    performanceBonus: 5200,
    lta: 3200,
    fixedAllowance: 2100,
    pfEmployee: 6240,
    pfEmployer: 6240,
    professionalTax: 200,
  },
  {
    id: '10',
    loginId: 'DAYMDS20230010',
    name: 'Meera Desai',
    email: 'meera.desai@dayflow.com',
    phone: '+91 98765 43219',
    avatar: getAvatar('Meera Desai'),
    designation: 'Data Analyst',
    department: 'Analytics',
    company: 'Dayflow Technologies',
    manager: 'Priya Patel',
    location: 'Pune, India',
    dateOfJoining: '2023-06-20',
    status: 'present',
    dateOfBirth: '1995-11-08',
    address: '12 Hinjewadi, Pune 411057',
    nationality: 'Indian',
    personalEmail: 'meera.d@gmail.com',
    gender: 'Female',
    maritalStatus: 'Married',
    bankName: 'Axis Bank',
    accountNumber: '****2345',
    ifscCode: 'UTIB0005678',
    panNo: 'BCDEF6789G',
    uanNo: '100123456798',
    empCode: 'EMP010',
    about: 'Data enthusiast who loves turning raw data into actionable insights.',
    whatILove: 'Working with data to drive business decisions.',
    interests: 'Data visualization, statistics, hiking, baking',
    skills: ['Python', 'SQL', 'Tableau', 'Excel', 'Machine Learning'],
    certifications: ['Google Data Analytics'],
    basicSalary: 50000,
    hra: 20000,
    standardAllowance: 10000,
    performanceBonus: 5000,
    lta: 3100,
    fixedAllowance: 2000,
    pfEmployee: 6000,
    pfEmployer: 6000,
    professionalTax: 200,
  },
  {
    id: '11',
    loginId: 'DAYSJI20230011',
    name: 'Sanjay Joshi',
    email: 'sanjay.joshi@dayflow.com',
    phone: '+91 98765 43220',
    avatar: getAvatar('Sanjay Joshi'),
    designation: 'Finance Manager',
    department: 'Finance',
    company: 'Dayflow Technologies',
    manager: 'Rajesh Kumar',
    location: 'Mumbai, India',
    dateOfJoining: '2022-11-01',
    status: 'present',
    dateOfBirth: '1985-02-28',
    address: '5 Nariman Point, Mumbai 400021',
    nationality: 'Indian',
    personalEmail: 'sanjay.j@gmail.com',
    gender: 'Male',
    maritalStatus: 'Married',
    bankName: 'HDFC Bank',
    accountNumber: '****6789',
    ifscCode: 'HDFC0009012',
    panNo: 'HIJKL0123M',
    uanNo: '100123456799',
    empCode: 'EMP011',
    about: 'Experienced finance professional with expertise in financial planning and analysis.',
    whatILove: 'Strategic financial planning and team collaboration.',
    interests: 'Financial markets, golf, reading, travel',
    skills: ['Financial Analysis', 'Budgeting', 'SAP', 'Excel', 'Forecasting'],
    certifications: ['CFA', 'CPA'],
    basicSalary: 90000,
    hra: 36000,
    standardAllowance: 18000,
    performanceBonus: 12000,
    lta: 6000,
    fixedAllowance: 3600,
    pfEmployee: 10800,
    pfEmployer: 10800,
    professionalTax: 200,
  },
  {
    id: '12',
    loginId: 'DAYKBN20230012',
    name: 'Kavita Bansal',
    email: 'kavita.bansal@dayflow.com',
    phone: '+91 98765 43221',
    avatar: getAvatar('Kavita Bansal'),
    designation: 'Marketing Lead',
    department: 'Marketing',
    company: 'Dayflow Technologies',
    manager: 'Rajesh Kumar',
    location: 'Mumbai, India',
    dateOfJoining: '2023-01-10',
    status: 'absent',
    dateOfBirth: '1991-06-15',
    address: '18 Juhu, Mumbai 400049',
    nationality: 'Indian',
    personalEmail: 'kavita.b@gmail.com',
    gender: 'Female',
    maritalStatus: 'Single',
    bankName: 'Yes Bank',
    accountNumber: '****0123',
    ifscCode: 'YESB0001234',
    panNo: 'NOPQR4567S',
    uanNo: '100123456800',
    empCode: 'EMP012',
    about: 'Creative marketer with a passion for brand storytelling and digital campaigns.',
    whatILove: 'The creative freedom and impact of our campaigns.',
    interests: 'Digital marketing, content creation, yoga, travel',
    skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Analytics', 'Social Media'],
    certifications: ['Google Ads', 'HubSpot Inbound'],
    basicSalary: 70000,
    hra: 28000,
    standardAllowance: 14000,
    performanceBonus: 7000,
    lta: 4500,
    fixedAllowance: 2800,
    pfEmployee: 8400,
    pfEmployer: 8400,
    professionalTax: 200,
  },
];

// Generate attendance records for the last 30 days
export const generateAttendanceRecords = (employeeId?: string): AttendanceRecord[] => {
  const records: AttendanceRecord[] = [];
  const today = new Date();
  
  employees.forEach(emp => {
    if (employeeId && emp.id !== employeeId) return;
    
    for (let i = 0; i < 30; i++) {
      const date = new Date(today);
      date.setDate(date.getDate() - i);
      
      // Skip weekends
      if (date.getDay() === 0 || date.getDay() === 6) continue;
      
      const isPresent = Math.random() > 0.2;
      const checkIn = isPresent ? `09:${String(Math.floor(Math.random() * 30)).padStart(2, '0')} AM` : null;
      const checkOut = isPresent ? `06:${String(Math.floor(Math.random() * 30) + 30).padStart(2, '0')} PM` : null;
      
      records.push({
        id: `${emp.id}-${date.toISOString().split('T')[0]}`,
        employeeId: emp.id,
        employeeName: emp.name,
        date: date.toISOString().split('T')[0],
        checkIn,
        checkOut,
        workHours: isPresent ? `${8 + Math.floor(Math.random() * 2)}h ${Math.floor(Math.random() * 60)}m` : '-',
        extraHours: isPresent && Math.random() > 0.7 ? `${Math.floor(Math.random() * 3)}h ${Math.floor(Math.random() * 60)}m` : '-',
      });
    }
  });
  
  return records.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
};

export const timeOffRequests: TimeOffRequest[] = [
  {
    id: '1',
    employeeId: '3',
    employeeName: 'Rajesh Kumar',
    startDate: '2025-01-03',
    endDate: '2025-01-07',
    type: 'paid',
    status: 'approved',
    days: 3,
  },
  {
    id: '2',
    employeeId: '8',
    employeeName: 'Ananya Singh',
    startDate: '2025-01-02',
    endDate: '2025-01-04',
    type: 'sick',
    status: 'approved',
    days: 2,
  },
  {
    id: '3',
    employeeId: '1',
    employeeName: 'Arjun Sharma',
    startDate: '2025-01-15',
    endDate: '2025-01-17',
    type: 'paid',
    status: 'pending',
    days: 3,
  },
  {
    id: '4',
    employeeId: '6',
    employeeName: 'Neha Srivastava',
    startDate: '2025-01-20',
    endDate: '2025-01-22',
    type: 'paid',
    status: 'pending',
    days: 3,
  },
  {
    id: '5',
    employeeId: '5',
    employeeName: 'Amit Gupta',
    startDate: '2024-12-28',
    endDate: '2024-12-30',
    type: 'unpaid',
    status: 'rejected',
    days: 3,
  },
  {
    id: '6',
    employeeId: '10',
    employeeName: 'Meera Desai',
    startDate: '2025-01-25',
    endDate: '2025-01-27',
    type: 'paid',
    status: 'pending',
    days: 3,
  },
];

// Current logged in user (for demo)
export const currentUser = employees[0]; // Arjun Sharma
